#!/usr/bin/env bash
# This is used to configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
# This is the  name of the custom HTTP header must be X-Served-By
# This is the value of the custom HTTP header must be the hostname of the server Nginx is running on
sudo apt-get update
sudo apt-get -y install nginx
#This is used to configure firewall to allow request through port 80
sudo ufw allow 'Nginx HTTP'
sudo mkdir -p /var/www/html
#This is used to change permissions to allow us to easily create files in this directory
sudo chmod -R 755 /var/www
#This is for creating the index page
echo 'Hello World!' |sudo tee  /var/www/html/index.html
