#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script

# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  Marley_frontend
        bind *:80
        mode http
        default_backend Marley_backend
backend besthor_backend
        balance roundrobin
        server 271821-web-01 18.235.255.205:80 check
        server 271821-web-02 54.90.27.193:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# Used to enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Used for testing the HAproxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Used to restart the Nginx service
sudo service haproxy restart
